### ISSUE TITLE
monotonic orthography (greek)

### ISSUE THREAD

**Issue by camillelab** [einars/translit.vim#3]
Hi! This plugin is really useful! Would it be possible to add the Greek tonos (΄) and diaeresis (¨) for the monotonic orthography of modern greek?

```
# acute
Άά Έέ Ήή Ίί Όό Ύύ Ώώ

# acute, diaeresis
ΐ ΰ

# diaeresis
Ϊϊ Ϋϋ
```

Best regards!

**Comment by einars** [comment]
Sure. The greek mapping is in these lines: https://github.com/einars/translit.vim/blob/master/plugin/translit.vim#L222-L224


    call TranslitAddMapping("greek",
        \ 'a:α, b:β, v:β, g:γ, d:δ, e:ε, z:ζ, h:η, th:θ, u:θ, i:ι, k:κ, l:λ, m:μ, n:ν, x:ξ,' .
        \ 'o:ο, p:π, r:ρ, s:σ, t:τ, y:υ, f:φ, ch:χ, ps:ψ, w:ω')

and it would need to be updated with the additional mappings (source letter combination:target letter).

What do you feel would be aproppriate mappings for the letters?

**Comment by camillelab** [comment]
Thanks! My first idea would be to put a special ASCII character before a vowel to indicate an accent. Here is a suggestion with - (acute), = (diaeresis) and + (both).

```
call TranslitAddMapping("greek",
    \ "a:α, b:β, v:β, g:γ, d:δ, e:ε, z:ζ, h:η, th:θ, u:θ, i:ι, k:κ, l:λ, m:μ, n:ν, x:ξ," .
    \ "o:ο, p:π, r:ρ, s:σ, t:τ, y:υ, f:φ, ch:χ, ps:ψ, w:ω," .
    \ "-a:ά, -e:έ, -h:ή, -i:ί, -o:ό, -y:ύ, -w:ώ, =i:ϊ, =y:ϋ, +i:ΐ, +y:ΰ" )
```

**Comment by einars** [comment]
A duplication of a letter is a very comfy way to add some accent, e.g in latvian, aa -> ā, but that makes sense if the accented letters are first class letters that occur frequently in the language and are not some rare-ish special cases.

How frequently do accented characters occur in the greek?

**Comment by camillelab** [comment]
The duplication of a letter is a more ergonomic solution. Tonos (acute) occurs in almost every word. On the other hand, diaeresis are rather scarce.

**Comment by einars** [comment]
It should probably be fine now. If you have some suggestions for improvement after using it for a bit, feel free to reopen and comment (or send ar pull request with changes).
